version: '3.6'

services:
  nginx-proxy:
    image: docker.comsave.nl:5000/comsave/nginx-proxy-letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    
networks:
 default:
   external:
     name: nginx-proxy
