version: '3.6'

services:
  nginx-proxy:
    image: docker.comsave.nl:5000/comsave/nginx-proxy-letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  web:
    image: docker.comsave.nl:5000/comsave/documentation:master
    ports:
      - 8989:8989
    environment:
      - VIRTUAL_HOST=staging.developer.comsave.com
    # depends_on:
    #   - nginx-proxy
