version: '3.6'

services:
  nginx-proxy:
    image: docker.comsave.nl:5000/comsave/nginx-proxy-letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - S3FS_ENDPOINT=https://s3.wasabisys.com
      - S3FS_ACCESSKEY=HTGT0EK60QR7KT3WA79I
      - S3FS_SECRETKEY=EmggKIe499mBQYOU1bETGLqDrawYr1nHzVsibPXY
      - LETSENCRYPT_EMAIL=joeri.veder@comsave.com
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://nginx-proxy:8888/v1/event/create
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://nginx-proxy:8888/v1/event/remove
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # deploy:
    #   labels:
    #     - com.df.notify=true
      #   - com.df.distribute=true
      #   - com.df.alertName=memlimit
      #   - com.df.alertIf=@service_mem_limit:0.8
      #   - com.df.alertFor=30s
      # placement:
      #   constraints: [node.role == manager]
      # resources:
      #   reservations:
      #     memory: 10M
      #   limits:
      #     memory: 20M

networks:
 default:
   external:
     name: nginx-proxy
